services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Upload\Http\UploadFileAction:
        tags: ['controller.service_arguments']
    App\Upload\Http\RetrieveFileAction:
        tags: ['controller.service_arguments']