services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        tags: [ "controller.service_arguments" ]

    App\Upload\Http\UploadFileAction:
    App\Upload\Http\RetrieveFileAction:
