imports:
    - { resource: ./actions.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    League\Flysystem\AdapterInterface: "@oneup_flysystem.local_adapter_adapter"
    League\Flysystem\FilesystemInterface: "@oneup_flysystem.local_filesystem"
