imports:
    - { resource: ./actions.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Upload\Files: '@App\Upload\FileRepository'
    App\Upload\FileSaver: '@App\Upload\FlysystemSaver'

    League\Flysystem\AdapterInterface: '@oneup_flysystem.local_adapter_adapter'
    League\Flysystem\FilesystemInterface: '@oneup_flysystem.local_filesystem'

    App\Upload\FileRepository:
    App\Upload\FlysystemSaver:
