imports:
    - { resource: ./actions.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\User\Entity\Users: '@App\User\Entity\UserRepository'

    App\User\Entity\UserRepository: