imports:
    - { resource: ./actions.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\User\Entity\UserRepository:
    App\User\Service\UserRegisterer:
        arguments:
            - '@App\User\Entity\UserRepository'
            - '@security.encoder_factory'
            - '@validator'