version: "3"

services:
    php:
        environment:
            - SYMFONY_ENV=test
            - DB_HOST=database_test

    database_test:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASS}
            - PGPASSWORD=${DB_PASS}
        tmpfs:
            - /var/lib/postgresql/data
