version: "3"

services:
    php:
        volumes:
            - "../.:/app"
            - "../docker/nginx/web/.:/web"
        environment:
            - PHP_IDE_CONFIG=serverName=${TARGET_HOST}

    front:
        volumes:
            - "../docker/nginx/web/.:/web"
        environment:
            - VIRTUAL_HOST=${TARGET_HOST}
            - VIRTUAL_PORT=80
