version: "3"

services:
    php:
        command: ["php-fpm", "--allow-to-run-as-root", "-d", "zend_extension=xdebug.so"]
        volumes:
            - "../.:/app"

    front:
        ports:
            - 0.0.0.0:8080:80
        environment:
            - VIRTUAL_HOST=template.docker
            - VIRTUAL_PORT=80
