api_users:
    resource: ../src/User/Http/
    type: annotation
    prefix: /api
    defaults:
        _format: json

api_doc:
    path: /api/doc
    methods: GET
    defaults: { _controller: Nelmio\ApiDocBundle\Controller\SwaggerUiController }