# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    App\Controller\:
#        resource: '../src/Controller'
#        tags: ['controller.service_arguments']

    App\Common\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
