# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

imports:
    - { resource: ./../src/Common/Resources/config/services.yaml }
    - { resource: ./../src/User/Resources/config/services.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Symfony\Component\Serializer\Normalizer\PropertyNormalizer:
        arguments:
            - "@serializer.mapping.class_metadata_factory"
            - "@serializer.name_converter.camel_case_to_snake_case"
            - "@property_info.reflection_extractor"
        tags: [ serializer.normalizer ]
#
#    Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
#            tags: [ serializer.normalizer ]