imports:
    - { resource: ./actions.yaml }
    - { resource: ./loaders.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Report\DataLoader:
        abstract: true