services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        tags: [ "controller.service_arguments" ]

    App\Post\Http\AddPostAction:
    App\Post\Http\LikePostAction:
