services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Post\Entity\TagExtractor: '@App\Post\Service\DoctrineTagsExtractor'

    App\Post\Service\TextTagExtractor:
    App\Post\Service\DoctrineTagsExtractor:
        arguments:
            - '@App\Post\Service\TextTagExtractor'
    App\Post\Entity\PostRepository:
        tags:
            - { name: 'app.repository', entity: 'App\Post\Entity\Post' }

    App\Post\Http\Transformer\LikeTransformer:
    App\Post\Http\Transformer\PostTransformer:

    App\Post\Handler\AddPostHandler:
        tags: [ 'broadway.command_handler' ]
    App\Post\Handler\LikePostHandler:
        tags: [ 'broadway.command_handler' ]