services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Security\Entity\Credentials: '@App\Security\Entity\CredentialRepository'

    App\Security\Entity\CredentialRepository:
    App\Security\CredentialsProvider:

