services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\User\Http\Transformer\UserTransformer:

    App\User\Entity\UserRepository:
        tags:
            - { name: 'app.repository', entity: 'App\User\Entity\User' }
    App\User\Handler\RegisterHandler:
        tags: [ 'broadway.command_handler' ]