services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    request_annotation_resolver:
        class: 'App\Core\Http\Annotation\HttpAnnotationResolver'
        public: true
        arguments:
            - '@controller_resolver'
            - '@annotations.reader'

    App\Core\Doctrine\Flush:
        public: true

    App\Core\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: 'default' }

    App\Core\EventListener\JsonRequestTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    App\Core\EventListener\KernelViewListener:
        arguments:
            - '@serializer'
            - '@request_annotation_resolver'
        tags:
            - { name: kernel.event_listener, event: kernel.view }

    App\Core\Http\PaginatorValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 1000 }

    App\Core\EventListener\DomainExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onDomainException }

    App\Core\Normalizer\CollectionNormalizer:
        tags: [ serializer.normalizer ]

    App\Core\Normalizer\CursorNormalizer:
        tags: [ serializer.normalizer ]

    App\Core\Normalizer\StringableObjectsNormalizer:
        tags: [ serializer.normalizer ]