services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    request_annotation_resolver:
        class: 'App\Core\Http\Annotation\HttpAnnotationResolver'
        public: true
        arguments:
            - '@controller_resolver'
            - '@annotations.reader'

    App\Core\Http\BaseAction:
        abstract: false
        tags: ['controller.service_arguments']
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    App\Core\Doctrine\MigrationEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: 'default' }

    App\Core\EventListener\JsonRequestTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    BornFree\TacticianDoctrineDomainEvent\EventListener\CollectsEventsFromAllEntitiesManagedByUnitOfWork:
    App\Core\EventListener\KernelViewListener:
        arguments:
            - '@serializer'
            - '@request_annotation_resolver'
        tags:
            - { name: kernel.event_listener, event: kernel.view }

    App\Core\EventListener\DomainExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onDomainException }

    App\Core\Normalizer\CollectionNormalizer:
        tags: [ serializer.normalizer ]

    App\Core\Normalizer\StringableNormalizer:
        tags: [ serializer.normalizer ]