imports:
    - { resource: ./actions.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Post\Entity\Posts: '@App\Post\Entity\PostRepository'
    App\Post\Entity\TagExtractor: '@App\Post\Service\TextTagExtractor'

    App\Post\Service\TextTagExtractor:
    App\Post\Entity\PostRepository: